spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: 1234
  messages:
    basename: i18n/messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: "EmilJafarov3841@gmail.com"
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 300000
  refresh-token:
    expiration: 3600000

 # mvc:
  #  servlet:
    #  path: /v1/api